### ISSUE TITLE
Unit of Amplitude

### ISSUE THREAD

**Issue by shinsid** [XingzhiMac/CAS741-Proj#12]
![Screenshot from 2020-10-17 14-38-29](https://user-images.githubusercontent.com/12082585/96350950-759fc880-1086-11eb-9722-6eeba2b96e30.png)

Should the unit of Amplitude be 'metres' in SI?

**Comment by smiths** [comment]
@shinsid, please either explain why the units are as indicated (watts?), or appropriately adjust them.  I feel like your units will be related to an electromagnetic wave.  I feel like a unit of power (watts) isn't the right unit, but I don't have expertise in this area.  :smile:.  If you do make a change to the SRS, please include the commit hash where the changed was added.

**Comment by XingzhiMac** [comment]
You are right, I made a mistake here. Both _A_ and _Asum_ should have no unit. _A_ and _Asum_ are just for mathematical analysis and do not have any physical meaning. 

Only _A''_ should have a unit and it should be Watt and here is the reason:

As I mentioned in SRS, the strength of a radio wave is defined as the power of the electric current the wave can generate, and an electric current is the movement of electric charge. If a stream of electric charge travels back and forth in an antenna, or in other words an alternating electric current flows in the antenna, the electric field in the space surrounding the antenna will also change up and down and presents as an emitting radio wave. Meanwhile, a periodic change in the electric field can also generate an alternating current in a "peaceful" antenna by moving the electric charge in it. All of these steps are energy conversions, from the energy to drive electric charge to the energy to change the electric field, and then back to the energy to drive electric charge. An intense undulation of the electric field gives the electric charge a more powerful push and generates an intense current, while a mild undulation drives the charge less powerfully and generates a weak current. (You can find more details at [https://en.wikipedia.org/wiki/Electric_field](url) and [https://en.wikipedia.org/wiki/Electromagnetic_radiation](url) )

But we are talking about current, why wouldn't we use Ampere? That's because our basic idea here is to find a measure of the general ability to generate electric currents. The magnitude of current in Amperes does not only depend on the electric field but also depends on the circuit itself. Like we know the brightness of the sun or a lightbulb does not depend on the sensitivity of our eyes, the strength of a radio wave should not depend on the observer device's characteristics. To eliminate the device-specific characteristics, engineers use power to represent the wave's true ability to generate currents.

**Comment by XingzhiMac** [comment]
I made commit 8526633c4ca1f6560e3f9b29b0fadc9289f2ef82 for this issue.

**Comment by smiths** [comment]
Great explanation @XingzhiMac, especially the last paragraph (But we are talking about current ...).  I did think that the right unit should be amps.  Now I understand why you use watts.  :smile:
