### ISSUE TITLE
Derviation of Phi_FORSxis not clear

### ISSUE THREAD

**Issue by shinsid** [XingzhiMac/CAS741-Proj#14]
![Screenshot from 2020-10-19 17-24-38](https://user-images.githubusercontent.com/12082585/96513455-24cbd380-1230-11eb-802e-cebea4f9fc10.png)

Hi Xingzhi,

Question - In the above derivation, I was wondering what happens to Phi_LOS ? Can you please clarify?

**Comment by XingzhiMac** [comment]
_λ_ is the wavelength, _c_ is the speed of light and f is the frequency of the signal. 
_c_ = _λf_
_1/λ_ = _f/c_ 
_2πΔd_ * (_1/λ_) = _2πΔd_ * _f/c_
Hope this could help you.

**Comment by smiths** [comment]
@XingzhiMac, I think @shinsid was looking for an explanation in your document, rather than just a comment.  Phi_LOS just seems to disappear between the second to last equation in the derivation and the last equation.  Your explanation above doesn't have a symbol for Phi_LOS.  I think we are just looking for an explanation (as part of the derivation) of how you get from the second to last equation to the last equation.

**Comment by shinsid** [comment]
Hi @XingzhiMac ,

Like Dr. Smith mentioned, my question was related to Phi_LOS. Sorry for the extra highlights in the picture. I do this often when I am reading through the document just for my understanding. The first two equations are absolutely clear.

**Comment by XingzhiMac** [comment]
@smiths @shinsid Sorry, I placed the essential statement in the table but forgot to mention it in the derivation. The equation holds as we take Phi_LOS as the reference (i.e. Phi_LOS = 0).
![image](https://user-images.githubusercontent.com/70971553/97647403-878b4f00-1a28-11eb-863e-00899527a2f4.png)
Hope this could answer your question. I will add that statement in the derivation. Thank you!

**Comment by shinsid** [comment]
It's clear now. Thanks ! :100:

**Comment by XingzhiMac** [comment]
@smiths @shinsid I pushed commit 432f9cd82a654452e4c6dc2d1a069d99510050d7 for this issue.

**Comment by smiths** [comment]
Great!
