### ISSUE TITLE
Units not clear

### ISSUE THREAD

**Issue by shinsid** [XingzhiMac/CAS741-Proj#7]
![Screenshot from 2020-10-17 14-24-18](https://user-images.githubusercontent.com/12082585/96350582-83ece500-1084-11eb-9f9f-a2eddc562a8e.png)

dBm and W - both point to unit power 

I am not 100% sure about dBm, but after a google search, I was thinking if 'electrical power' would be the right explanation for this.

Also, maybe for rad,  'angle' is enough than 'phase angle' (Not sure, just a suggestion)

**Comment by XingzhiMac** [comment]
I think these are 2 issues lol
1) dBm is the logarithmic representation of milliWatt. Since milliWatt is a unit of any type of power, dBm should be the same. But you are not wrong, dBm is mostly (and perhaps only) used in the field of electrical engineering.
2) Thanks for your suggestion. I use rad to represent the quantitative measurement of the phase difference between two sinusoidal waves (i.e. phase angle), which I want to distinguish it from geometric angles.
